function modelPath = build_oven_simulink(p)
%BUILD_OVEN_SIMULINK Rigenera il modello V3 attivo; versioni precedenti in Git.
if nargin < 1, p = oven_defaults(); end
folder = fileparts(mfilename('fullpath'));
addpath(folder);
model = 'oven_model';
modelPath = fullfile(folder,[model '.slx']);
if bdIsLoaded(model)
    assert(strcmp(get_param(model,'Dirty'),'off'),'oven:unsaved', ...
        'Il modello V3 contiene modifiche non salvate: salvarle prima di rigenerarlo.');
    close_system(model,0);
end
if exist(modelPath,'file')
    load_system(modelPath);
    Simulink.BlockDiagram.deleteContents(model);
else
    new_system(model);
end
ws = get_param(model,'ModelWorkspace');
ws.assignin('ovenV3_p',p);
g = oven_geometry(p);
ws.assignin('ovenV3_g',g);
set_param(model,'Solver','ode15s','SolverType','Variable-step', ...
    'RelTol',num2str(p.sim.relTol),'AbsTol',num2str(p.sim.absTol), ...
    'MaxStep',num2str(p.sim.maxStep),'StopTime', ...
    'ovenV3_p.sim.warmupSeconds+ovenV3_p.sim.bakeSeconds+ovenV3_p.sim.recoverySeconds', ...
    'ReturnWorkspaceOutputs','on','SaveTime','on','TimeSaveName','tout', ...
    'InitFcn','oven_refresh_model(bdroot);', ...
    'PreLoadFcn','addpath(fileparts(get_param(bdroot,''FileName'')));');
add_block('simulink/Sources/Step',[model '/Inserimento due pizze'], ...
    'Time','ovenV3_p.sim.warmupSeconds','Before','0','After','1', ...
    'Position',[35 75 70 105]);
add_block('simulink/Sources/Step',[model '/Estrazione due pizze'], ...
    'Time','ovenV3_p.sim.warmupSeconds+ovenV3_p.sim.bakeSeconds', ...
    'Before','0','After','1','Position',[35 145 70 175]);
add_block('simulink/Math Operations/Sum',[model '/Pizze presenti'], ...
    'Inputs','+-','Position',[135 90 160 150]);
add_block('simulink/User-Defined Functions/Level-2 MATLAB S-Function', ...
    [model '/Bilanci termici multizona'], 'FunctionName','oven_sfun', ...
    'Parameters','ovenV3_p,ovenV3_g','Position',[235 85 425 160]);
add_block('simulink/Sinks/To Workspace',[model '/Stati SI'], ...
    'VariableName','oven_states','SaveFormat','Structure With Time', ...
    'Position',[540 25 665 55]);
add_line(model,'Inserimento due pizze/1','Pizze presenti/1','autorouting','on');
add_line(model,'Estrazione due pizze/1','Pizze presenti/2','autorouting','on');
add_line(model,'Pizze presenti/1','Bilanci termici multizona/1','autorouting','on');
add_line(model,'Bilanci termici multizona/1','Stati SI/1','autorouting','on');
names = {'forno','dischi','pizze'};
indices = {[g.idx.gas g.idx.shell g.idx.fixed g.idx.hearth], ...
    g.idx.plate(:)',[g.idx.base(:)' g.idx.top(:)']};
for k=1:3
    selector = ['Temperature ' names{k}];
    converter = ['Celsius ' names{k}];
    scope = ['Grafico ' names{k}];
    yy = 90+(k-1)*110;
    add_block('simulink/Signal Routing/Selector',[model '/' selector], ...
        'NumberOfDimensions','1','IndexMode','One-based', ...
        'IndexOptionArray',{'Index vector (dialog)'},'Indices',mat2str(indices{k}), ...
        'InputPortWidth','-1','Position',[510 yy 555 yy+40]);
    add_block('simulink/Math Operations/Bias',[model '/' converter], ...
        'Bias','-273.15','Position',[610 yy 665 yy+40]);
    add_block('simulink/Sinks/Scope',[model '/' scope], ...
        'Position',[730 yy 765 yy+40]);
    add_line(model,'Bilanci termici multizona/1',[selector '/1'],'autorouting','on');
    add_line(model,[selector '/1'],[converter '/1'],'autorouting','on');
    add_line(model,[converter '/1'],[scope '/1'],'autorouting','on');
end
note = Simulink.Annotation(model,sprintf(['FORNO V3 | due dischi rotanti 320 mm\n' ...
    'Parametri: Model Workspace > ovenV3_p. Unita interne: K, kg, s, W.\n' ...
    'Bilanci: oven_rhs.m. Settori e strati: oven_geometry.m.\n' ...
    'Modello preliminare non calibrato; tiraggio e irraggiamento semplificati.']));
note.Position = [30 380 780 455];
set_param(model,'SimulationCommand','update');
save_system(model,modelPath);
fprintf('Modello Simulink creato: %s\n',modelPath);
end
