function p = oven_defaults()
%OVEN_DEFAULTS Parametri SI, preliminari e non calibrati sperimentalmente.
p.version = '3.0';
p.ambient = 298.15;
p.sigma = 5.670374419e-8;
p.geom.width = .79;
p.geom.frontDepth = .41;
p.geom.rearWidth = .51;
p.geom.rearDepth = .14;
p.geom.plateDiameter = .32;
p.geom.plateCenters = [.21 .205; .58 .205]; % x,y dalla bocca anteriore
p.geom.plateClearance = .001; % gioco radiale meccanico da verificare
p.geom.roofShape = 'barrel'; % sezione parabolica, non arco circolare
p.geom.height = .25; % quota massima interna
p.geom.rise = .10; % altezza massima meno altezza all'imposta
p.geom.mouthWidth = .60;
p.geom.mouthHeight = .13;
p.geom.hatchWidth = .20;
p.geom.hatchHeight = .10;
p.geom.hatchOpenFraction = 0;
p.geom.sectors = 8;
p.floor.thickness = .01;
p.floor.rho = 2600;
p.floor.cp = 900;
p.floor.k = 2.5;
p.floor.emissivity = .85;
p.roof.material = 'steel'; % steel | refractory; proprieta' ipotizzate
p.roof.steel = struct('thickness',.002,'rho',7800,'cp',500,'k',45);
p.roof.refractory = struct('thickness',.03,'rho',2100,'cp',900,'k',1.3);
p.roof.emissivity = .8;
p.insulation.thickness = .05;
p.insulation.k = .055;
p.insulation.outsideH = 10;
p.flow.chimneyDiameter = .10;
p.flow.chimneyHeight = .50;
p.flow.chimneyPosition = 'front'; % front | rear, cambia rete advettiva
p.flow.chimneyLoss = 3;
p.flow.inletLoss = 2;
p.flow.inletFraction = .30; % frazione area bocca efficace per aria entrante
p.flow.mixingKgS = .012; % ricircolo simmetrico indipendente dal tiraggio
p.flow.cp = 1100;
p.flow.pressure = 101325;
p.flow.gasConstant = 287;
p.flow.gravity = 9.81;
p.fuel.kgH = 3.5;
p.fuel.lhv = 15e6;
p.fuel.efficiency = .70;
p.fuel.radiantFraction = .35;
p.fuel.radiantWeights = [.15 .60 .25]; % volta frontale, posteriore, focolare
p.heat.gasH = 18;
p.heat.pizzaH = 12;
p.heat.contactH = 150;
p.heat.pizzaInternalH = 90;
p.heat.shellLink = 1.5; % W/K
p.heat.rearExposureMean = .18;
p.heat.rearExposureAmplitude = .12; % gradiente spaziale parametrico, non CFD
p.heat.openingEmissivity = .8;
p.rotation.rpm = [2 2];
p.rotation.initialPhase = [0 0];
p.pizza.diameter = .30; % lascia margine su disco da 32 cm
p.pizza.mass = .25; % per pizza, massa nominale a capacita' costante
p.pizza.cp = 2500;
p.pizza.baseMassFraction = .40;
p.pizza.waterFraction = .50;
p.pizza.initialTemperature = 298.15;
p.pizza.emissivity = .9;
p.pizza.latentHeat = 2.26e6;
p.pizza.evaporationTemperature = 373.15;
p.pizza.evaporationTransitionK = 2; % regolarizzazione ebollizione, non coeff. empirico
p.pizza.waterTransitionKg = 1e-5; % acqua per pizza sotto cui raccordare all'asciutto
p.sim.warmupSeconds = 1800;
p.sim.bakeSeconds = 90;
p.sim.recoverySeconds = 90;
p.sim.outputStep = 5;
p.sim.maxStep = 2;
p.sim.relTol = 1e-5;
p.sim.absTol = 1e-7;
end
