import * as T from 'three';
import {OrbitControls} from './vendor/OrbitControls.js';
const $=id=>document.getElementById(id);
try {
const selected=new URLSearchParams(location.search).get('model');const thermalMode=selected==='thermal';const preheatMode=selected==='preheat';const bakeMode=selected==='bake';const dataRoot=preheatMode?'./preheat-data/':bakeMode?'./bake-data/':thermalMode?'./thermal-data/':'./data/';if(thermalMode)document.querySelector('footer b').nextElementSibling.textContent='Prototipo termico da 25 °C: combustione di gas equivalente al legno con rilascio prescritto e conduzione nei materiali. Non calcola pirolisi dei ciocchi, evaporazione o rotazione della pizza. I colori delle geometrie solide sono illustrativi; la sezione mostra la temperatura del gas.';if(preheatMode){document.querySelector('h1').textContent='Preriscaldamento V4';document.querySelector('footer b').nextElementSibling.textContent='Forno vuoto: 60 minuti fisici di preriscaldamento completati sul PC di casa. Fiamma, fumo e sezione del gas provengono dalla nuova run FDS. Le superfici si scaldano nel modello termico; i loro colori in questa vista sono illustrativi. Per valutare il calore della volta e del piano servono le temperature di parete e i flussi nei risultati FDS.';document.querySelector('footer b').nextElementSibling.nextElementSibling.textContent='Sorgente di gas equivalente al legno a rilascio prescritto; non è una pirolisi calibrata della quercia. Le soglie di temperatura del piano e della volta sono verificabili nel report di questa run.';}if(bakeMode){document.querySelector('h1').textContent='Cottura V4 · 120 s';document.querySelector('footer b').nextElementSibling.textContent='Due pizze sono state inserite dopo il preriscaldamento di 60 minuti. Questi campi provengono dalla run FDS di cottura completata sul PC di casa; le temperature del cibo sono riportate nelle sonde e nel report, mentre i colori della geometria sono illustrativi.';document.querySelector('footer b').nextElementSibling.nextElementSibling.textContent='La cottura è stata lanciata con deroga alle soglie di forno pronto: il piano non aveva raggiunto 430 °C. La simulazione rappresenta cibo omogeneo e fermo, con calore latente apparente; non valuta doratura, evaporazione o rotazione.';} const response=await fetch(dataRoot+'volume.json');if(!response.ok)throw Error('Dati CFD non disponibili');
const data=await response.json(), c=data.case;
const renderer=new T.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setClearColor(0x101820);$('scene').append(renderer.domElement);
const scene=new T.Scene(), camera=new T.PerspectiveCamera(42,1,.01,20);camera.up.set(0,0,1);camera.position.set(1.4,-1.6,1.25);
const controls=new OrbitControls(camera,renderer.domElement);controls.target.set(.395,.31,.25);controls.enableDamping=true;
scene.add(new T.HemisphereLight(0xffffff,0x65707a,2));const light=new T.DirectionalLight(0xffffff,3);light.position.set(1,-1,3);scene.add(light);
function box(w,d,h,x,y,z,color){let m=new T.Mesh(new T.BoxGeometry(w,d,h),new T.MeshStandardMaterial({color,roughness:.8}));m.position.set(x,y,z);scene.add(m);return m;}
box(.79,.41,.025,.395,.205,-.013,0xb4a487);box(.72,.08,.025,.395,-.04,-.013,0xb4a487);
const rear=new T.Shape();rear.moveTo(0,.41);rear.lineTo(.79,.41);rear.lineTo(.65,.66);rear.lineTo(.14,.66);rear.closePath();const back=new T.Mesh(new T.ShapeGeometry(rear),new T.MeshStandardMaterial({color:0x8f806b,side:T.DoubleSide}));scene.add(back);
if(c.pizza_present!==false)for(const [x,y] of c.pizza_centers){for(const [r,h,z,col] of [[.16,.012,.006,0xe2d4b6],[.15,.009,.016,0xd29b56]]){let m=new T.Mesh(new T.CylinderGeometry(r,r,h,64),new T.MeshStandardMaterial({color:col,roughness:1}));m.rotation.x=Math.PI/2;m.position.set(x,y,z);scene.add(m);}const ring=new T.Mesh(new T.TorusGeometry(.142,.008,8,64),new T.MeshStandardMaterial({color:0xeac18a}));ring.position.set(x,y,.021);scene.add(ring);}
const positions=[],indices=[];for(let j=0;j<=32;j++){let y=j*.66/32,edge=y<=.41?0:(y-.41)/.25*.14;for(let i=0;i<=40;i++){let x=edge+(c.width-2*edge)*i/40;positions.push(x,y,.19+.09*(1-((x-.395)/(.395-edge))**2));if(j<32&&i<40){let a=j*41+i;indices.push(a,a+1,a+41,a+1,a+42,a+41);}}}
let roofGeo=new T.BufferGeometry();roofGeo.setAttribute('position',new T.Float32BufferAttribute(positions,3));roofGeo.setIndex(indices);roofGeo.computeVertexNormals();let roof=new T.Mesh(roofGeo,new T.MeshStandardMaterial({color:0x9bbed1,transparent:true,opacity:.12,side:T.DoubleSide,depthWrite:false}));scene.add(roof);
let tube=new T.Mesh(new T.CylinderGeometry(.065,.065,1.12,48,1,true),new T.MeshStandardMaterial({color:0x9bbed1,transparent:true,opacity:.1,side:T.DoubleSide,depthWrite:false}));tube.rotation.x=Math.PI/2;tube.position.set(.395,.045,.72);scene.add(tube);
const lineMat=new T.LineBasicMaterial({color:0x6e8c9e});const outline=[new T.Vector3(0,-.08,0),new T.Vector3(.79,-.08,0),new T.Vector3(.79,.41,0),new T.Vector3(.65,.66,0),new T.Vector3(.14,.66,0),new T.Vector3(0,.41,0),new T.Vector3(0,-.08,0)];scene.add(new T.Line(new T.BufferGeometry().setFromPoints(outline),lineMat));
const clouds=[];
for(const m of data.meshes){let n=m.shape.reduce((a,b)=>a*b,1),pos=new Float32Array(n*3);let q=0;for(const z of m.coordinates.z)for(const y of m.coordinates.y)for(const x of m.coordinates.x){pos[q++]=x;pos[q++]=y;pos[q++]=z;}
for(const kind of ['smoke','fire']){const res=await fetch(dataRoot+m[kind].file);if(!res.ok)throw Error('Volume mancante');let bytes=new Uint8Array(await res.arrayBuffer());if(bytes.length!==n*m[kind].times.length)throw Error('Dimensioni volume non valide');let geo=new T.BufferGeometry();geo.setAttribute('position',new T.BufferAttribute(pos,3));geo.setAttribute('intensity',new T.BufferAttribute(new Float32Array(n),1));
let mat=new T.ShaderMaterial({transparent:true,depthWrite:false,blending:kind==='fire'?T.AdditiveBlending:T.NormalBlending,uniforms:{fire:{value:kind==='fire'?1:0}},vertexShader:'attribute float intensity; varying float v; void main(){v=intensity;vec4 p=modelViewMatrix*vec4(position,1.0);gl_Position=projectionMatrix*p;gl_PointSize=clamp(19.0/(-p.z),2.0,60.0);}',fragmentShader:'uniform float fire; varying float v; void main(){float r=length(gl_PointCoord-.5)*2.;if(r>1.||v<.015)discard;float a=pow(1.-r*r,2.);vec3 col=mix(vec3(.48,.52,.56),mix(vec3(1.,.12,.008),vec3(1.,.95,.45),sqrt(v)),fire);gl_FragColor=vec4(col,a*min(v*.32,.28));}'});let obj=new T.Points(geo,mat);scene.add(obj);clouds.push({m,n,bytes,kind,obj});}}
const slice=data.slices.find(s=>s.quantity==='TEMPERATURE'&&s.axis===0&&s.mesh===1);let thermal;
const velocities=['U-VELOCITY','V-VELOCITY','W-VELOCITY'].map(q=>data.slices.find(s=>s.quantity===q&&s.axis===0&&s.mesh===1));
const arrows=[];if(velocities.every(Boolean)){const v=velocities[0],nx=v.coordinates.x.length,ny=v.coordinates.y.length;for(let k=0;k<v.coordinates.z.length;k+=2)for(let j=0;j<ny;j+=2){let origin=new T.Vector3(v.coordinates.x[0],v.coordinates.y[j],v.coordinates.z[k]);if(origin.z<0||origin.z>.31||origin.y<-.08||origin.y>.66)continue;let arrow=new T.ArrowHelper(new T.Vector3(0,0,1),origin,.02,0x65dfe2,.008,.005);scene.add(arrow);arrows.push({arrow,index:nx*(j+ny*k)});}}
if(slice){let pos=[];for(let z of slice.coordinates.z)for(let y of slice.coordinates.y)for(let x of slice.coordinates.x)pos.push(x,y,z);let g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(pos,3));g.setAttribute('color',new T.Float32BufferAttribute(new Float32Array(pos.length),3));thermal=new T.Points(g,new T.PointsMaterial({size:.028,vertexColors:true,transparent:true,opacity:.65,depthWrite:false}));scene.add(thermal);}
let frame=-1,playing=true,last=0;const times=data.meshes[0].fire.times;$('timeline').max=times.length-1;
function drawFrame(f){frame=f;$('timeline').value=f;$('time').textContent=preheatMode?(times[f]/60).toFixed(1)+' min':times[f].toFixed(1)+' s';for(const item of clouds){let idx=item.m[item.kind].times.reduce((a,t,i)=>Math.abs(t-times[f])<Math.abs(item.m[item.kind].times[a]-times[f])?i:a,0);let a=item.obj.geometry.attributes.intensity.array,scale=item.kind==='smoke'?Math.min(20,item.m.smoke.maxima[idx]*8700*.025*4):1;for(let i=0;i<item.n;i++)a[i]=item.bytes[idx*item.n+i]/254*scale;item.obj.geometry.attributes.intensity.needsUpdate=true;}
if(arrows.length){const ix=velocities[0].times.reduce((a,t,i)=>Math.abs(t-times[f])<Math.abs(velocities[0].times[a]-times[f])?i:a,0);for(const {arrow,index} of arrows){const v=new T.Vector3(...velocities.map(s=>s.values[ix][index]));const speed=v.length();arrow.userData.active=speed>.03;if(speed>.03){arrow.setDirection(v.normalize());arrow.setLength(Math.min(.09,speed*.025),.008,.005);}}}
if(thermal){let ix=slice.times.reduce((a,t,i)=>Math.abs(t-times[f])<Math.abs(slice.times[a]-times[f])?i:a,0);let col=new T.Color(),a=thermal.geometry.attributes.color.array;slice.values[ix].forEach((v,i)=>{col.setHSL((1-T.MathUtils.clamp((v-25)/975,0,1))*.66,1,.5);col.toArray(a,i*3);});thermal.geometry.attributes.color.needsUpdate=true;}}
$('play').onclick=()=>{playing=!playing;$('play').textContent=playing?'Pausa':'Riprendi';};$('timeline').oninput=()=>{playing=false;$('play').textContent='Riprendi';drawFrame(+$('timeline').value);};
new ResizeObserver(()=>{let r=$('scene').getBoundingClientRect();renderer.setSize(r.width,r.height);camera.aspect=r.width/r.height;camera.updateProjectionMatrix();}).observe($('scene'));
$('status').textContent=`${times.length} istanti · ${data.meshes.length} domini CFD`;
drawFrame(0);function animate(now){requestAnimationFrame(animate);if(playing&&now-last>220){drawFrame((frame+1)%times.length);last=now;}for(let v of clouds)v.obj.visible=$(v.kind).checked;for(const {arrow} of arrows)arrow.visible=$('air').checked&&arrow.userData.active;roof.visible=tube.visible=$('shell').checked;if(thermal)thermal.visible=$('temp').checked;controls.update();renderer.render(scene,camera);}requestAnimationFrame(animate);
async function status(){try{if(bakeMode){const r=await fetch('./bake-data/summary.json',{cache:'no-store'});if(!r.ok)return;const s=await r.json();$('thermal-status').textContent=`Run completata a 120 s: pizza 1 ${s.pizzas[0].surface_min_C.toFixed(0)}–${s.pizzas[0].surface_max_C.toFixed(0)} °C; pizza 2 ${s.pizzas[1].surface_min_C.toFixed(0)}–${s.pizzas[1].surface_max_C.toFixed(0)} °C in superficie. Il forno era sotto la soglia di preriscaldamento.`;const a=document.createElement('a');a.href='./bake-video/v4_cfd_fiamma_fumi.mp4';a.textContent=' Apri il video MP4';a.style.color='#ffd18a';$('thermal-status').append(a);return;}if(preheatMode){const r=await fetch('./preheat-data/summary.json',{cache:'no-store'});if(!r.ok)return;const s=await r.json();const p=s.readiness.measured;$('thermal-status').textContent=`Run completata: piano minimo ${p.floor_min_C.toFixed(1)} °C; volta minima ${p.vault_min_C.toFixed(1)} °C. Criteri di preriscaldamento ${s.readiness.ready?'raggiunti':'non raggiunti'}.`;const a=document.createElement('a');a.href='./preheat-video/v4_cfd_fiamma_fumi.mp4';a.textContent=' Apri il video MP4';a.style.color='#ffd18a';$('thermal-status').append(a);return;}const r=await fetch('./data/thermal-status.json',{cache:'no-store'});if(!r.ok)return;const s=await r.json();$('thermal-status').textContent=s.status==='completed'?'Prototipo termico: run completata. I risultati separati sono disponibili nella cartella thermal-data.':s.status==='failed'?'Prototipo termico: run interrotta, consultare il log.':'Prototipo termico: calcolo in corso (60 s fisici, partenza a freddo). La vista sopra mostra il caso di riferimento già completato.';if(s.status==='completed'&&!thermalMode){const link=document.createElement('a');link.href='?model=thermal';link.textContent=' Apri il risultato termico 3D';link.style.color='#ffd18a';$('thermal-status').append(link);}}catch{}}status();setInterval(status,30000);
}catch(e){$('error').textContent=e.message;$('status').textContent='Impossibile caricare la vista';console.error(e);}


