function s = run_draft_checks()
%RUN_DRAFT_CHECKS Verifiche preliminari geometriche e di pressione, non CFD.
here=fileparts(mfilename('fullpath')); out=fullfile(here,'results');
if ~exist(out,'dir'), mkdir(out); end
a=oven_draft_defaults();
s.base=a; s.closed=oven_draft_network(a);
op=a; op.doorOpen=true; s.open=oven_draft_network(op);
s.validation=validate_draft_network(a);
[p,d]=oven_dimension_defaults(); c=struct('frontDepth',.08,'flueY',.045);
g=oven_compact_front_geometry(p,d,c); s.geometry=g;
s.roofDropAtCollarEdgeM=p.geom.rise*(d.collarDiameter/p.geom.width)^2;
s.roofOverMouthSideM=p.geom.height-p.geom.rise*(p.geom.mouthWidth/p.geom.width)^2;
s.fixedBridgeBetweenCutoutsM=diff(p.geom.plateCenters(:,1))-p.geom.plateDiameter-2*p.geom.plateClearance;
s.frontStoneBridgeM=min(p.geom.plateCenters(:,2))-p.geom.plateDiameter/2-p.geom.plateClearance;
% Raccordo di 19 cm sopra una volta parabolica: occorre un adattatore,
% non una flangia piana appoggiata direttamente sulla superficie curva.
assert(s.roofOverMouthSideM>p.geom.mouthHeight);
assert(s.fixedBridgeBetweenCutoutsM>0 && s.frontStoneBridgeM>0);

% Scenari scelti per separare i principali effetti; non probabilita.
names={'Base chiusa';'Presa 30 cm2';'Presa 90 cm2';'Camino 0.5 m'; ...
    'Camino 1.5 m';'Diametro 15 cm';'Fumi 150 C';'Fumi 100 C'; ...
    'Perdite K=8';'Vento avverso 3 Pa';'Vento avverso 6 Pa'; ...
    'Legna 3.5 kg/h';'Porta aperta';'Aperta, gas 300 C'; ...
    'Aperta, camino 1.5 m';'Chiusa H1.5 A90';'H1.5 A90 T150 K8 vento3'};
cases=repmat({a},numel(names),1);
cases{2}.inletArea=30e-4; cases{3}.inletArea=90e-4;
cases{4}.chimneyH=.5; cases{5}.chimneyH=1.5; cases{6}.chimneyD=.15;
cases{7}.flueK=150+273.15; cases{8}.flueK=100+273.15;
cases{9}.minorK=8; cases{10}.windAdversePa=3; cases{11}.windAdversePa=6;
cases{12}.fuelKgH=3.5;
cases{13}=op; cases{14}=op; cases{14}.chamberK=300+273.15;
cases{15}=op; cases{15}.chimneyH=1.5;
cases{16}.chimneyH=1.5; cases{16}.inletArea=90e-4;
cases{17}=cases{16}; cases{17}.flueK=150+273.15;
cases{17}.minorK=8; cases{17}.windAdversePa=3;
rows=cell(numel(names),1); s.cases=cases; s.network=cell(size(cases));
for k=1:numel(names)
    q=cases{k}; r=oven_draft_network(q); s.network{k}=r;
    [amin,margin]=airRequirement(q,2);
    rows{k}=table(string(names{k}),q.doorOpen,100*q.chimneyD,q.chimneyH, ...
        q.flueK-273.15,q.inletArea*1e4,q.fuelKgH,q.minorK,q.windAdversePa, ...
        r.lambdaTotal,r.lambdaRear,3600*r.stackKgS,3600*r.doorOutKgS, ...
        r.pressureDoorTopPa,amin*1e4,margin,r.sensibleChamberKW, ...
        r.requiresStoredHeat,r.reverseStack,r.massResidualKgS, ...
        'VariableNames',{'name','doorOpen','diameterCm','heightM','flueC','inletCm2', ...
        'fuelKgH','minorK','windPa','lambdaTotal','lambdaRear','stackKgH', ...
        'doorOutKgH','doorTopPa','inletRequiredForLambda2Cm2','marginLambda2Pa', ...
        'sensibleKW','requiresStoredHeat','reverseStack','massResidualKgS'});
end
s.rows=vertcat(rows{:});
% Maglia di sensibilita chiusa: stessa temperatura di camera, aria imposta
% dalle pressioni; tutti i casi includono massa combustibile nei fumi.
s.temperaturesC=[100 150 250 350];
s.areasCm2=20:10:120;
s.lambdaGrid=zeros(numel(s.temperaturesC),numel(s.areasCm2));
for i=1:numel(s.temperaturesC)
    for j=1:numel(s.areasCm2)
        q=a; q.flueK=s.temperaturesC(i)+273.15; q.inletArea=s.areasCm2(j)*1e-4;
        r=oven_draft_network(q); s.lambdaGrid(i,j)=r.lambdaRear;
    end
end
% Il Cd di una bocca calda non e ricavato per analogia da un prodotto.
s.doorCd=[.5 .65 .8]; s.doorSensitivity=zeros(3,3);
for k=1:3
    q=op; q.cdDoor=s.doorCd(k); r=oven_draft_network(q);
    s.doorSensitivity(k,:)=[r.doorOutKgS*3600 r.pressureDoorTopPa r.sensibleChamberKW];
end
writetable(s.rows,fullfile(out,'verifiche_fumi.csv'));
save(fullfile(out,'verifiche_fumi.mat'),'s');
drawChecks(s,out);
writeReport(s,out);
disp(s.rows(:,{'name','lambdaRear','doorOutKgH','marginLambda2Pa'}));
fprintf('Residuo massimo bilancio massa: %.3g kg/s.\n',max(abs(s.rows.massResidualKgS)));
end

function [area,margin]=airRequirement(a,lambda)
% Porta chiusa, aria richiesta stechiometrica * lambda: budget pressione.
if a.doorOpen, area=NaN; margin=NaN; return; end
rhoA=a.pressure/(a.gasConstant*a.ambientK);
rhoC=a.pressure/(a.gasConstant*a.chamberK);
rhoF=a.pressure/(a.gasConstant*a.flueK);
stoich=((8/3)*a.dryC+8*a.dryH-a.dryO)/a.oxygenMassFraction;
ma=lambda*stoich*(1-a.moistureWet)*a.fuelKgH/3600;
mf=a.fuelKgH/3600*(1-(1-a.moistureWet)*a.dryAsh);
areaF=pi*a.chimneyD^2/4;
K=a.minorK+a.darcyF*a.chimneyH/a.chimneyD;
B=a.gravity*((a.roofZ-a.inletZ)*(rhoA-rhoC)+a.chimneyH*(rhoA-rhoF));
left=B-a.windAdversePa-K*(ma+mf)^2/(2*rhoF*areaF^2);
if left>0, area=ma/(a.cdInlet*sqrt(2*rhoA*left)); else, area=Inf; end
margin=left-ma^2/(2*rhoA*(a.cdInlet*a.inletArea)^2);
end

function drawChecks(s,out)
fig=figure('Visible','off','Theme','light','Color','w','Scrollable','off', ...
    'Position',[50 50 1400 650]);
guard=onCleanup(@()close(fig));
tiledlayout(1,2,'Padding','loose','TileSpacing','loose');
nexttile; hold on;
colors=lines(4);
for k=1:4
    plot(s.areasCm2,s.lambdaGrid(k,:),'LineWidth',2,'Color',colors(k,:));
end
yline(1,'--','Aria teorica');
yline(2,':','Riferimento di confronto');
xlabel('Presa posteriore: area libera netta [cm²]');
ylabel('Aria disponibile / aria stechiometrica, lambda');
legend(compose('Fumi medi %d °C',s.temperaturesC),'Location','southeast');
grid on; title({'Porta chiusa — tubo Ø13, H 1 m, K=4';'Legna 4,5 kg/h; temperature assegnate'});
nexttile; hold on;
a=s.base; ra=a.pressure/(a.gasConstant*a.ambientK);
rc=a.pressure/(a.gasConstant*a.chamberK);
z=linspace(0,a.doorHeight,150);
closed=s.closed.pressureFloorPa+a.gravity*(ra-rc)*z;
opened=s.open.pressureFloorPa+a.gravity*(ra-rc)*z;
plot(closed,100*z,'LineWidth',2);
plot(opened,100*z,'LineWidth',2);
xline(0,'--','Ambiente');
yline(100*s.open.neutralHeightM,':','Piano neutro a porta aperta');
xlabel('Pressione camera − esterno [Pa]'); ylabel('Quota sulla bocca [cm]');
legend('Porta chiusa, sola presa bassa','Bocca interamente aperta','Location','southwest');
title({'Bocca 72 × 16 cm — modello uniforme 1D';'Pressione positiva: tendenza al flusso verso fuori'});
grid on;
exportgraphics(fig,fullfile(out,'verifiche_fumi.png'),'Resolution',150);
end

function writeReport(s,out)
fid=fopen(fullfile(out,'VERIFICHE_COMPATTA.md'),'w','n','UTF-8');
assert(fid>=0); guard=onCleanup(@()fclose(fid));
a=s.base;
fprintf(fid,'# Verifiche della variante compatta\n\n');
fprintf(fid,['**Esito:** compatibilita nominale in pianta confermata; appoggio sulla volta ' ...
    'e ingombri tridimensionali ancora da dettagliare. ' ...
    'Camino e captazione a porta aperta non approvati come progetto costruttivo. ' ...
    'La rete di pressione individua condizioni favorevoli e criticita sotto ipotesi esplicite.\n\n']);
fprintf(fid,'## Geometria\n\n');
fprintf(fid,['Piano 79 x 41 cm, retro 25 cm, avancorpo 8 cm: profondita nominale 74 cm. ' ...
    'Porta-bordo dischi 12.5 cm, porta-centri 28.5 cm. Raccordo Ø19 dietro la porta ' ...
    'con 3 cm nominali, solo margine geometrico.\n\n' ...
    'Con gioco radiale ipotizzato 1 mm: ponte fisso tra i tagli %.1f mm, ' ...
    'ponte anteriore %.1f mm. Non verificata resistenza della cordierite o dilatazione. ' ...
    'La volta e %.1f cm sopra il piano ai lati della bocca alta 16 cm. ' ...
    'La curvatura produce %.1f mm di dislivello fra centro e bordo laterale del raccordo: ' ...
    'serve un adattatore sagomato. Non e una flangia piana direttamente posata sulla volta.\n\n'], ...
    1000*s.fixedBridgeBetweenCutoutsM,1000*s.frontStoneBridgeM, ...
    100*s.roofOverMouthSideM,1000*s.roofDropAtCollarEdgeM);
fprintf(fid,['**Sovrapposizione ammessa:** collare e presa sulla volta possono stare sopra ' ...
    'le pizze in pianta. Il criterio e la distanza verticale del collettore dal volume ' ...
    'utile, non la separazione dei loro contorni dall''alto. La formula della volta ' ...
    'descrive il tratto sopra il piano; il profilo dell''avancorpo di 8 cm e il sostegno ' ...
    'anteriore del raccordo non sono ancora dettagliati.\n\n']);
fprintf(fid,['Pala ipotizzata 34 cm: passaggio 72 cm lascia solo 5 mm per lato nel caso ' ...
    'allineato a ciascun disco. Sono esclusi telaio, tolleranze, variazioni utensile ' ...
    'e verifica della manovra. Il focolare contiene due file di ciocchi 25 x 7 cm ' ...
    'nelle distanze nominali gia definite: non dimostra autonomia o potenza del fuoco.\n\n']);
fprintf(fid,'## Ipotesi riproducibili\n\n');
fprintf(fid,['Legna %.1f kg/h, umidita tal quale %.0f%%, aria teorica %.3f kg/kg secco. ' ...
    'Il riferimento lambda=2 e solo una scelta di confronto. Temperatura gas camera ' ...
    '%.0f C uniforme, media camino %.0f C, ambiente %.0f C. Non sono temperature ' ...
    'calcolate dal modello termico. Tubo Ø%.0f cm, altezza verticale sopra il tetto %.1f m, ' ...
    'K locale complessivo %.1f, fattore Darcy %.2f, Cd presa e bocca %.2f. ' ...
    'Coefficienti ipotizzati, senza misura di raccordo, griglia, letto di braci o terminale. ' ...
    'Presa posteriore bassa: %.0f cm² LIBERI NETTI, centro a %.0f cm sopra il piano.\n\n'], ...
    a.fuelKgH,100*a.moistureWet,s.closed.airStoichKgPerKgDry,a.chamberK-273.15, ...
    a.flueK-273.15,a.ambientK-273.15,a.chimneyD*100,a.chimneyH,a.minorK,a.darcyF,a.cdInlet, ...
    a.inletArea*1e4,a.inletZ*100);
fprintf(fid,['La rete risolve la pressione della camera e conserva la massa di aria piu ' ...
    'combustibile gasificato (ceneri escluse). Con porta aperta integra separatamente ' ...
    'entrata e uscita lungo l''altezza; non impone tutta la bocca come ingresso. ' ...
    'Vento positivo ostacola lo scarico. La massa di legna resta imposta anche se manca aria: ' ...
    'lambda basso segnala un''ipotesi di combustione incompatibile, non una combustione simulata.\n\n']);
fprintf(fid,'## Risultati\n\n');
fprintf(fid,'| Scenario | lambda presa posteriore | Uscita bocca kg/h | Margine a lambda=2 Pa |\n|---|---:|---:|---:|\n');
for k=1:height(s.rows)
    r=s.rows(k,:);
    fprintf(fid,'| %s | %.2f | %.1f | %.2f |\n',char(r.name),r.lambdaRear,r.doorOutKgH,r.marginLambda2Pa);
end
fprintf(fid,['\nMargine positivo: pressione sufficiente alla portata richiesta nelle sole ipotesi del caso. ' ...
    'Margine negativo: il riferimento lambda=2 non e raggiunto. Non sono un giudizio di sicurezza ' ...
    'o una prova di buona combustione. NaN: riferimento non applicato alla porta aperta.\n\n']);
fprintf(fid,['**Base a porta chiusa:** lambda %.2f; per lambda=2 servono circa %.0f cm² netti ' ...
    'nel caso base. Il valore cambia con temperatura, perdite e vento. Una griglia al 60%% ' ...
    'di area libera richiede un''area lorda pari a quella netta divisa per 0.60, prima di ' ...
    'considerare le sue perdite aggiuntive. Una misura come 20 x 3 cm e 60 cm² lordi, ' ...
    'non necessariamente netti.\n\n'],s.closed.lambdaRear,s.rows.inletRequiredForLambda2Cm2(1));
fprintf(fid,['**Porta aperta:** nel caso base il piano neutro e a %.1f cm, sotto il bordo alto ' ...
    'a 16 cm. La rete prevede flusso uscente in alto (%.1f kg/h di gas, non massa di fumo o CO). ' ...
    'Variando Cd bocca 0.50/0.65/0.80, l''uscita calcolata e %.1f/%.1f/%.1f kg/h. ' ...
    'E un segnale che il semplice foro nel tetto non supera questa verifica semplificata. ' ...
    'La portata reale non e validata: mancano stratificazione, inerzia del getto, deflettore, ' ...
    'raccolta tridimensionale e vento variabile. Lambda totale include aria dalla porta ' ...
    'che puo non raggiungere il fuoco; in inversione include anche aria entrata dal camino. ' ...
    'Non prova adeguata alimentazione della legna.\n\n'], ...
    100*s.open.neutralHeightM,s.open.doorOutKgS*3600,s.doorSensitivity(:,1));
fprintf(fid,['**Controllo energetico condizionato:** si assume che tutti i gas lascino il ' ...
    'volume camera alla sua temperatura uniforme; il raffreddamento nel tubo avviene dopo. ' ...
    'La temperatura media assegnata alla canna serve a calcolarne la densita e non e la ' ...
    'temperatura all''uscita dalla camera. L''estrazione sensibile nel caso aperto e %.1f kW, ' ...
    'contro %.1f kW di potenza rilasciata ipotizzata, prima di radiazione e altre perdite. ' ...
    'Se la prima supera la seconda, le temperature imposte non sono sostenibili a regime: ' ...
    'il caso rappresenta soltanto uno stato caldo transitorio alimentato anche dall''accumulo. ' ...
    'Non e stato risolto il raffreddamento nel tempo.\n\n'],s.open.sensibleChamberKW,s.open.fuelReleasedKW);
fprintf(fid,'## Conseguenze per la prossima geometria\n\n');
fprintf(fid,['- Mantenere 8 cm come avanzamento candidato: le sole pressioni non ne verificano l''effetto.\n' ...
    '- Prevedere una presa posteriore regolabile con area libera misurabile; verificare ' ...
    '60 e 90 cm² come scenari, insieme al percorso attraverso/sopra le braci.\n' ...
    '- Confrontare altezza camino 1 e 1.5 m; l''altezza superiore non risolve da sola la bocca aperta. ' ...
    'I confronti Ø15 sono solo idraulici: tubo, raccordo e ingombri vanno riselezionati.\n' ...
    '- Disegnare un collettore/deflettore alto anteriore con transizione graduale verso il tubo, ' ...
    'poi verificare l''uscita durante apertura della porta. Nessuna sezione minima definitiva e dedotta qui.\n' ...
    '- Provare accensione, regime, ricarica posteriore e apertura frontale con misura di ' ...
    'temperature fumi, pressione differenziale, consumo/umidita legna e osservazione dei fumi; ' ...
    'O2/CO nei fumi servono a valutare la combustione. Ripetere sotto vento.\n\n']);
fprintf(fid,'## Equazioni e fonti\n\n');
fprintf(fid,['`rho = p/(R T)`; `P(z) = P0 + g(rho_a-rho_c)z`; ' ...
    '`DeltaP_camino = P0 + g(rho_a-rho_c)z_tetto + gH(rho_a-rho_f) - P_vento`; ' ...
    '`Ktot = Klocali + f_D H/D`; `m = A sqrt(2 rho DeltaP / Ktot)`.\n\n' ...
    'Aria secca teorica: `[(8/3)C + 8H - O] / xO2`, con C/H/O frazioni massiche ' ...
    'su base secca. Massa secca = massa tal quale x (1-umidita).\n\n' ...
    '- [USDA, Wood as a Fuel](https://www.srs.fs.usda.gov/pubs/gtr/gtr_so024.pdf): ' ...
    'composizione media del legno e bilancio stechiometrico; l''eccesso d''aria riportato ' ...
    'nel manuale non prescrive quello di questo forno.\n' ...
    '- [NIST CONTAM 3.2](https://nvlpubs.nist.gov/nistpubs/TechnicalNotes/NIST.TN.1887.pdf): ' ...
    'reti di pressione, orifizi, aperture con flussi in entrambe le direzioni, sezione Doorways.\n' ...
    '- [NISTIR 89-4035](https://nvlpubs.nist.gov/nistpubs/Legacy/IR/nistir89-4035.pdf): ' ...
    'tiraggio idrostatico e perdite nei condotti.\n\n']);
fprintf(fid,['**Validazione numerica:** %d controlli superati; massimo residuo di massa %.3g kg/s. ' ...
    'Questo verifica il calcolo, non la fedelta al forno reale.\n\n' ...
    'Riproduzione: `s = run_draft_checks();`. Parametri in `oven_draft_defaults.m`; ' ...
    'risultati completi in verifiche_fumi.csv e verifiche_fumi.mat, grafico verifiche_fumi.png.\n'], ...
    numel(s.validation.checks),max(abs(s.rows.massResidualKgS)));
end
