function write_dimension_report(s)
%WRITE_DIMENSION_REPORT Sintesi numerica dello studio con ipotesi esplicite.
out=fullfile(fileparts(mfilename('fullpath')),'results');
if ~exist(out,'dir'),mkdir(out);end
fid=fopen(fullfile(out,'RISULTATI_DIMENSIONI.md'),'w','n','UTF-8');
assert(fid>=0,'Impossibile aprire il rapporto.');
guard=onCleanup(@()fclose(fid));
p=s.p; d=s.d; g=s.g;
fprintf(fid,'# Dimensionamento preliminare — risultati\n\n');
fprintf(fid,['**Candidato geometrico, non progetto esecutivo:** profondita totale %.0f cm ' ...
    '= %.0f cappa + %.0f piano + %.0f focolare. Piano %.0f x %.0f cm, dischi Ø%.0f cm.\n\n'], ...
    g.overallDepth*100,d.hoodDepth*100,p.geom.frontDepth*100,p.geom.rearDepth*100, ...
    p.geom.width*100,p.geom.frontDepth*100,p.geom.plateDiameter*100);
fprintf(fid,['Raccordo di ingombro Ø%.0f cm dentro cappa %.0f cm, con %.1f cm davanti/dietro. ' ...
    'Distanza ingresso esterno–bordo dischi %.1f cm; ingresso–centri %.1f cm.\n\n'], ...
    100*d.collarDiameter,100*d.hoodDepth,100*min(g.collarMargins(3:4)), ...
    100*g.frontedgeToPlateNear(1),100*g.frontedgeToPlateCenter(1));
fprintf(fid,['**Porta sul fronte esterno:** battuta coincidente con l''ingresso a y = %.1f cm. ' ...
    'Dall''esterno verso l''interno: porta, cappa con presa del camino, camera con due pizze, focolare. ' ...
    'L''asse del camino e %.1f cm verso l''interno rispetto alla porta. ' ...
    'Il passaggio a y = 0 resta permanentemente aperto fra camera e cappa, senza porta interna. ' ...
    'Apertura della porta e passaggio della camera: %.0f x %.0f cm.\n\n'], ...
    100*g.doorSeatY,100*(g.flueCenter(2)-g.doorSeatY),100*p.geom.mouthWidth,100*p.geom.mouthHeight);
fprintf(fid,['Legna lunga %.0f cm, spessore ipotizzato %.0f cm: %.0f file trasversali geometricamente ' ...
    'compatibili. Profondita minima per le %.0f file richieste %.0f cm, nei margini ipotizzati.\n\n'], ...
    100*d.woodLength,100*d.woodThickness,g.maxWoodRows,d.desiredRows,100*g.woodMinRearDepth);
fprintf(fid,['Il preriscaldamento termina alla media superiore dischi di %.0f C. ' ...
    'Caso base: combustibile %.1f kg/h, potenza immessa %.1f kW; due pizze di %.0f g e Ø%.0f cm per 90 s. ' ...
    'La soglia e un riferimento di confronto, non un criterio di cottura.\n\n'], ...
    d.targetPlateC,p.fuel.kgH,p.fuel.kgH/3600*p.fuel.lhv*p.fuel.efficiency/1000, ...
    1000*p.pizza.mass,100*p.pizza.diameter);
fprintf(fid,'| Caso | Raggiunge %.0f C entro %.0f min | Preriscaldamento min | Volta anteriore al carico C | Calo dischi nei 90 s K |\n', ...
    d.targetPlateC,d.maxPreheatSeconds/60);
fprintf(fid,'|---|---|---:|---:|---:|\n');
for k=1:height(s.rows)
    r=s.rows(k,:);
    if r.reached
        fprintf(fid,'| %s | si | %.1f | %.1f | %.1f |\n',char(r.name), ...
            r.preheatMinutes,r.shellFrontC_atLoad,r.dropUpperPlateBakeK);
    else
        fprintf(fid,'| %s | no, finale %.1f C | — | — | — |\n',char(r.name),r.endPreheatPlateC);
    end
end
fprintf(fid,['\nLe due prove finali usano 4.5 kg/h. Il caso con pietra 20 mm si confronta ' ...
    'con il precedente a 4.5 kg/h e 10 mm: lo spessore modifica piano fisso, dischi e focolare.\n']);
dry=s.rows.reached & s.rows.water90g_perPizza<1;
if any(dry)
    fprintf(fid,['\n**Limite quantitativo emerso:** in %d dei %d casi caricati il modello porta ' ...
        'l''acqua residua sotto 1 g per pizza. L''asciugatura troppo rapida segnala la necessita di ' ...
        'un modello di trasporto interno dell''umidita e di dati di prova. Il calo di temperatura ' ...
        'della pietra non va assunto come valore atteso sul prototipo.\n'],sum(dry),sum(s.rows.reached));
end
fprintf(fid,['\nLe differenze sono previsioni del modello non calibrato. Non costituiscono ' ...
    'una graduatoria di configurazioni ottimali. Il maggiore volume posteriore non aumenta ' ...
    'automaticamente la potenza di combustione: la portata di legna resta imposta.\n\n' ...
    '**Cappa:** verificata in pianta; assente come volume dai bilanci termici V3. ' ...
    'I risultati di tiraggio non verificano aspirazione, diluizione o fuoriuscita di fumo.\n\n' ...
    '**Porta chiusa:** il collegamento geometrico fra camera e camino rimane aperto, ' ...
    'ma il funzionamento a porta chiusa non e simulato. La V3 conserva ingresso d''aria imposto ' ...
    'e bocca aperta; l''alimentazione dell''aria di combustione a porta chiusa va dimensionata ' ...
    'separatamente. La geometria non dimostra il funzionamento con chiusura ermetica.\n\n' ...
    'Ridurre diametro o altezza del camino per trattenere piu calore non dimostra un tiraggio ' ...
    'adeguato: i requisiti di raccolta e scarico fumi restano da verificare.\n\n' ...
    '**Pizza:** asciugatura e contatto sono ancora semplificati; leggere il calo termico ' ...
    'come risposta al carico del modello, non come prova di cottura reale.\n\n']);
if isfield(s,'validation')
    fprintf(fid,'Verifiche dimensionali eseguite: vedere struttura validation in study.mat.\n\n');
end
fprintf(fid,'Quote e motivazioni: [LEGGIMI](../LEGGIMI.md). Dati completi: summary.csv e study.mat.\n');
end
